'database': 'pmnt'
'developer': 'Kachan Olga'
'docs': '-'
'file_dir': 'C:\Users\okachan\Documents\втб\файлы\dag\1416 - pmnt - Платёжные сервисы\new_json'
'id_ris': '1416'
'loadType': 'Scd0AppendPartition'
'mapping_version': '1.0'
'subo_name': '1416'
'system_target': '1642_19 Озеро данных'
'topic': 'pmnt'
